apiVersion: v1
kind: Namespace
metadata:
  name: frontendnamespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: frontendnamespace
data:
  REACT_APP_SERVER_URL: "http://backend-service-url:8080/employees"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
  namespace: frontendnamespace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:  
        - name: mainfrontendcr
          image: jayantsampletech/frontend:v1
          env:
            - name: REACT_APP_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: REACT_APP_SERVER_URL 
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  namespace: frontendnamespace
spec:
  type: LoadBalancer
  selector:
    app: frontendapp
  ports:
    - port: 3000           
      targetPort: 3000      
