version: "3.9"

services:
  database:
    image: postgres:15
    container_name: my_postgres_db
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  backend:
    image: jayantsampletech/backend:v1
    container_name: ubuntu-backend-1
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend.env
    networks:
      - app-network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    depends_on:
      backend:
    env_file:
      - frontend.env
    container_name: ubuntu-frontend-1
    networks:
      - app-network
    ports:
      - "3000:80"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
