apiVersion: v1
kind: Namespace
metadata:
  name: backendnamespace
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backendnamespace
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==  # 'mypassword'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: backendnamespace
data:
  DB_HOST: <url of the postgresqldb >
  DB_PORT: "5432"
  DB_USER: myuser
  DB_NAME: mydb
  ALLOWED_ORIGINS: <loadbalancer url of react app >
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
  namespace: backendnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - name: gobackendcontainer
          image: jayantsampletech/backend:v1  
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_NAME
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: ALLOWED_ORIGINS
---
apiVersion: v1
kind: Service
metadata:
  name: backendservice
  namespace: backendnamespace
spec:
  type: ClusterIP  
  selector:
    app: backendapp
  ports:
    - port: 8080
      targetPort: 8080
