apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backendnamespace
spec:
  type: LoadBalancer
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080