apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  namespace: frontendnamespace
spec:
  type: LoadBalancer
  selector:
    app: frontendapp
  ports:
    - port: 3000
      targetPort: 3000